/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module LAB2_cs303 (
  input X1,
  input X0,
  input Y1,
  input Y0,
  output A1,
  output A0
);
  assign A0 = (X0 & Y0);
  assign A1 = (((~ X1 & X0 & Y1) | (X1 & ~ X0 & Y0)) | ((X0 & ~ Y0 & Y1) | (X1 & Y0 & ~ Y1)));
endmodule
